<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Transliterate</AssemblyName>
    <RootNamespace>SubtitleEdit.Plugins.Transliterate</RootNamespace>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Plugin-Shared\Plugin-Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Projektanker.Icons.Avalonia" Version="9.6.2" />
    <PackageReference Include="Projektanker.Icons.Avalonia.MaterialDesign" Version="9.6.2" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Transliterate.Tests" />
  </ItemGroup>

</Project>
