name: Build .NET Framework Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    #    strategy:
    #      matrix:
    #        plugin: [ 'NoRecursiveDash', 'HIColorer', 'HI2UC', 'LinesUnbreaker' ]

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      
      # Setup NuGet
      - name: Setup NuGet
        uses: nuget/setup-nuget@v2
      
      #- uses: actions/cache@v4
      #  id: cache
      #  with:
      #    path: ~/.nuget/packages
      #    key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      # Restore NuGet packages
      - name: Restore NuGet packages
        # if: steps.cache.outputs.cache-hit != 'true'
        run: nuget restore "source\Plugins.Filter.slnf"
      
      # Build the solution
      - name: Build solution
        run: msbuild "source\Plugins.Filter.slnf" /p:Configuration=Release /p:SkipSharedProject=true

      - name: Create archives
        shell: pwsh
        run: source\zip-plugin-files.ps1
      
      #      - name: Upload Artifact (All)
      #        uses: actions/upload-artifact@v4
      #        with:
      #          name: Plugins
      #          path: C:\plugins\*.dll
    call-upload-artifacts-workflow:
      - use: ./github/workflows/upload-artifacts.yml
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: ${{matrix.plugin}}
#          path: C:\plugins\${{matrix.plugin}}.dll
