name: Build .NET Framework Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      
      # Setup NuGet
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
      
      # Restore NuGet packages
      - name: Restore NuGet packages
        run: nuget restore "source\Plugins.Filter.slnf"
      
      # Build the solution
      - name: Build solution
        run: msbuild "source\Plugins.Filter.slnf" /p:Configuration=Release /p:SkipSharedProject=true
      
      # Run tests (optional)
      #- name: Run tests
      #run: |
      #vstest.console.exe path\to\your\test\project.dll

      - name: Create archives
        shell: pwsh
        run: source\zip-plugin-files.ps1

      - name: Upload Artifact (All)
        uses: actions/upload-artifact@v4
        with:
          name: Plugins
          path: C:\plugins\*.zip

      - name: Upload Artifact (HI2UC)
        uses: actions/upload-artifact@v4
        with:
          name: HI2UC
          path: C:\plugins\HI2UC.zip

      - name: Upload Artifact (HIColorer)
        uses: actions/upload-artifact@v4
        with:
          name: HIColorer
          path: C:\plugins\HIColorer.zip

      - name: Upload Artifact (TightHyphen)
        uses: actions/upload-artifact@v4
        with:
          name: TightHyphen
          path: C:\plugins\TightHyphen.zip

      - name: Upload Artifact (LinesUnbreaker)
        uses: actions/upload-artifact@v4
        with:
          name: LinesUnbreaker
          path: C:\plugins\LinesUnbreaker.zip
          
      - name: Upload Artifact (NoRecursiveDash)
        uses: actions/upload-artifact@v4
        with:
          name: NoRecursiveDash
          path: C:\plugins\NoRecursiveDash.zip
