name: Build .NET Framework Project

on:
  push:
    branches:
      - main
      - github-actions
  pull_request:
    branches:
      - main

jobs:
  build-job:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      
      # Setup NuGet
      - name: Setup NuGet
        uses: nuget/setup-nuget@v2
      
      #- uses: actions/cache@v4
      #  id: cache
      #  with:
      #    path: ~/.nuget/packages
      #    key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      # Restore NuGet packages
      - name: Restore NuGet packages
        # if: steps.cache.outputs.cache-hit != 'true'
        run: nuget restore "source\Plugins.Filter.slnf"
      
      # Build the solution
      - name: Build solution
        run: msbuild "source\Plugins.Filter.slnf" /p:Configuration=Release

      # Copy dll to target directory
      - name: Create archives
        shell: pwsh
        run: source\zip-plugin-files.ps1

      # Upload plugins/artifacts
      - name: Upload HI2UC
        uses: ./.github/workflows/plugin-upload
        with:
          file-name: HI2UC

      - name: Upload HIColorer
        uses: ./.github/workflows/plugin-upload
        with:
          file-name: HIColorer