name: Upload artifacts

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        plugin: [ 'NoRecursiveDash', 'HIColorer', 'HI2UC', 'LinesUnbreaker' ]

    steps:
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.plugin}}
          path: C:\plugins\${{matrix.plugin}}.dll